### PR TITLE
Helidon v2.0.0 update

### PR DESCRIPTION
**Pull request by aberinnj**
- Updated frontend (nextjs, dockerized and OKE)
- Updated backend (APIS)
- Added ingress
- Updated scripts
- Updated terraform (OKE Issue)
- Removed unused artifacts

### CODE REVIEW

**Comment by aberinnj** [comment]
Accompanying documentation was successfully merged: https://github.com/oracle-livelabs/developer/pull/238
@Kuassim

**Comment by aberinnj** [comment]
@Kuassim I updated the licenses as well

**Comment by aberinnj** [comment]
The lab is using Ingress to deploy the frontend on OKE. Should I include the following license https://github.com/kubernetes/ingress-nginx/blob/main/LICENSE

@Kuassim

**Review by Kuassim — COMMENTED** [review]
Approved.

**Pull request merged**
